// <auto-generated />
using System;
using Desafio.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio.Data.Migrations
{
    [DbContext(typeof(DesafioContext))]
    partial class DesafioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio.Domain.Entities.Titulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CPFDevedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomeDevedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroDaParcela")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTitulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ParcelaDivida")
                        .HasColumnType("int");

                    b.Property<int>("PorcentagemJuros")
                        .HasColumnType("int");

                    b.Property<int>("PorcentagemMulta")
                        .HasColumnType("int");

                    b.Property<int>("ValorDaParcela")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("titulos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ff32602-b9cf-4ec6-965f-5335e03fd08a"),
                            CPFDevedor = "00000000000",
                            DataVencimento = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            NomeDevedor = "Devedor de teste",
                            NumeroDaParcela = 0,
                            NumeroTitulo = "000001",
                            ParcelaDivida = 1,
                            PorcentagemJuros = 5,
                            PorcentagemMulta = 10,
                            ValorDaParcela = 100000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
